name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["CC=icc FC=ifort", "CC=icx FC=ifx"]

    steps:

    # See https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html
    - name: install-intel
      run: |
        cd /tmp
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
        echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

    - name: checkout-pfunit
      uses: actions/checkout@v2
      with:
        repository: Goddard-Fortran-Ecosystem/pFUnit
        path: pfunit

    - name: cache-pfunit
      id: cache-pfunit
      uses: actions/cache@v2
      with:
        path: ~/pfunit
        key: pfunit-${{ runner.os }}-${{ matrix.compilers }}

    - name: build-pfunit
      if: steps.cache-pfunit.outputs.cache-hit != 'true'
      run: |
        cd pfunit
        mkdir build
        cd build
        ${{ matrix.compilers }} cmake .. -DSKIP_MPI=YES -DSKIP_ESMF=YES -DSKIP_FHAMCREST=YES -DCMAKE_INSTALL_PREFIX=~/pfunit -DCMAKE_BUILD_TYPE=Release
        make -j2 VERBOSE=1
        make install

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: sfcio
        submodules: true

    - name: build
      run: |
        cd sfcio
        mkdir build 
        cd build
        ${{ matrix.compilers }} cmake .. -DENABLE_TESTS=ON -DCMAKE_PREFIX_PATH="~/pfunit"
        make -j2 VERBOSE=1
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/sfcio/build
        make test VERBOSE=1

