name: llm-code-review
on: [workflow_dispatch,pull_request]

jobs:
  llm-code-review:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      GH_API_KEY: ${{ secrets.GH_API_KEY }}

    steps:

    - name: "Code review"
      uses: AlexanderRichert-NOAA/ci-llm-code-review@develop
      with:
        backend: gh-gpt-4o
        api-key-variable: GH_API_KEY
        reference-owner: AlexanderRichert-NOAA
        reference-branch: develop
        prompt-text: "Create a code review for the following file diff. Structure the review as 'Summary of changes,' 'Possible errors,' and 'Suggestions' with possible better approaches if appropriate. Infer functionality from throughout the code but focus your review solely on the new and removed lines indicated by + and - symbols.\n"
